'/admin/', 'Admin Home'
'/admin/usertype/all', 'User Types'
'/admin/usertype/create', 'Create'
'/admin/doctype/all', 'Document Types'
'/admin/doctype/create', 'Create'
'/admin/workflow/all', 'Workflows'
'/admin/workflow/create', 'Create'
'/admin/template/list', 'Document Templates'
'/admin/template/create', 'Create'
'/admin/role/all', 'Roles'
'/admin/role/create', 'Create'
'/admin/role/:roleId/edit', 'Edit'
'/admin/role/:roleId/permissions', 'Permissions'
'/admin/user/admin/:userId/edit', 'Edit'
'/admin/user/admin/:userId/view', 'Details'
'/admin/user/admin/:userId/password', 'Change Password'
'/admin/user/create', 'Create'
'/admin/user/admin/:userId/permissions', 'Permissions'
'/admin/project/all', 'Projects'
'/admin/project/type/all', 'Project Types'
'/admin/project/type/create', 'Create'
'/admin/project/create', 'Create'
'/admin/project/type/:projectTypeId/edit', ':projectTypeName'
'/admin/project/admin/:projectId', 'Redirect'
'/admin/project/admin/:projectId/edit', 'Edit'
'/admin/project/admin/:projectId/team', 'Team'
'/admin/project/admin/:projectId/resources/:filePoolId/edit', 'Files'
'/admin/meta/metatemplate/all', 'Meta Templates'
'/admin/meta/metatemplate/create', 'Create'
'/admin/meta/metatemplate/:metatemplateId/edit', ':metatemplateName'
'/admin/usertype/:userTypeId/edit', 'Edit'
'/admin/usertype/:userTypeId/permissions', 'Permissions'
'/admin/doctype/:docTypeId/edit', ':docTypeName'
'/admin/serversettings/', 'Taskboard'
'/admin/workflow/:workflowId/edit', 'Edit'
'/admin/template/:doctemplateId/edit', 'Edit'
'/admin/components', 'Components'
'/document/:documentId/references/:bibId/edit', 'Edit'
'/document/:documentId/references/create', 'Create'
'/document/:documentId/references/edit', 'Edit References'
'/document/:documentId/references/view', 'References'
'/taxonomies/', 'Taxonomies'
'/taxonomies/concepttype/all', 'Concept Types'
'/taxonomies/concepttype/create', 'Create'
'/taxonomies/concept/create', 'Create'
'/taxonomies/concept/search', 'Concepts'
'/taxonomies/taxonomytype/all', 'Taxonomy Types'
'/taxonomies/taxonomytype/create', 'Create'
'/taxonomies/relationshiptype/all', 'Relationship Types'
'/taxonomies/relationshiptype/create', 'Create'
'/taxonomies/taxonomytype/:taxonomytypeId/view', ':taxonomytypeName'
'/taxonomies/taxonomytype/:taxonomytypeId/edit', ':taxonomytypeName'
'/taxonomies/concepttype/:concepttypeId/view', ':concepttypeName'
'/taxonomies/concepttype/:concepttypeId/edit', ':concepttypeName'
'/taxonomies/relationshiptype/:relationshiptypeId/view', ':relationshiptypeName'
'/taxonomies/relationshiptype/:relationshiptypeId/edit', ':relationshiptypeName'
'/taxonomies/concept/:conceptId/view', ':conceptName'
'/taxonomies/concept/:conceptId/edit', ':conceptName'
'/document/:documentId', 'View'
'/document/:documentId/view', 'View'
'/document/:documentId/summary', 'Summary'
'/document/:documentId/text', 'Text'
'/document/:documentId/edit', 'Text'
'/document/:documentId/docpack', 'Translations'
'/document/:documentId/readability', 'Readability'
'/document/:documentId/releasenotes/releasenote/:noteId/edit', 'Edit'
'/document/:documentId/releasenotes/releasenote/create', 'Create'
'/document/:documentId/releasenotes', 'Release Notes'
'/document/:documentId/diff', 'Diff'
'/document/:documentId/preassignments', 'Assignments'
'/document/:documentId/meta/:metaid/view', 'view'
'/document/:documentId/meta/:metaid/edit', 'edit'
'/document/:documentId/references/:bibId/edit', 'Edit'
'/document/:documentId/references/create', 'Create'
'/document/:documentId/references/edit', 'Edit References'
'/document/:documentId/references/view', 'References'
'/document/:documentId/tables', 'Tables Switch'
'/document/:documentId/tables/edit', 'Edit'
'/document/:documentId/tables/view', 'View'
'/document/:documentId/tables/create', 'Create'
'/document/:documentId/tables/table/:tableId/edit', 'Edit'
'/document/:documentId/tables/table/:tableId/view', 'View'
'/document/:documentId/questions/create', 'Create'
'/document/:documentId/questions/question/:questionId/edit', 'Edit'
'/document/:documentId/questions/all', 'Questions'
'/document/:documentId/questions/', 'Questions'
'/document/:documentId/questions', 'Questions'
'/document/:documentId/images/:imagePoolId/edit', 'Images'
'/document/:documentId/images/:imagePoolId/view', 'Images'
'/document/:documentId/images/:imagePoolId/image/:imageId/edit', 'Edit'
'/document/:documentId/images/:imagePoolId/image/:imageId/view', 'View'
'/document/:documentId/images', 'Images'
'/document/:documentId/resources/:filePoolId/view', 'Files'
'/document/:documentId/resources/:filePoolId/edit', 'Files'
'/document/:documentId/resources/:filePoolId/view', 'Files'
'/document/:documentId/resources/:filePoolId/edit', 'Files'
'/document/:documentId/images/:imagePoolId/edit', 'Images'
'/document/:documentId/images/:imagePoolId/view', 'Images'
-- '/document/:documentId/meta/:metaId/view', 'view'
-- '/document/:documentId/meta/:metaId/edit', 'edit'
'/admin/project/all', 'Projects'
'/admin/project/type/all', 'Project Types'
'/admin/project/type/create', 'Create'
'/admin/project/create', 'Create'
'/admin/project/type/:projectTypeId/edit', ':projectTypeName'
'/admin/project/admin/:projectId', 'Redirect'
'/admin/project/admin/:projectId/edit', 'Edit'
'/admin/project/admin/:projectId/team', 'Team'
'/admin/project/admin/:projectId/resources/:filePoolId/edit', 'Files'
'/project', 'Projects'
'/project/user', 'Projects'
'/project/user/:projectId', 'todo'
'/project/user/:projectId/summary', 'Summary'
'/project/user/:projectId/team', 'Team'
'/project/user/:projectId/taskboard', 'Tasks'
'/project/user/:projectId/resources', 'Files'
'/project/user/:projectId/taskboard/work', 'Work'
'/project/user/:projectId/taskboard/outline', 'Outline'
'/reports', 'Reports'
'/reports/all', 'Reports'
'/reports/jobs', 'Jobs'
'/reports/report/jobs', 'Jobs'
'/reports/create', 'Create'
'/reports/report/:reportId/edit', 'Edit'
'/reports/report/:reportId/history', 'History'
'/reports/report/:reportId', 'Report'
'/document/:documentId/tables', 'Tables Switch'
'/document/:documentId/tables/edit', 'Edit'
'/document/:documentId/tables/view', 'View'
'/document/:documentId/tables/create', 'Create'
'/tasks/', 'Tasks'
'/tasks/checkedout', 'Checked Out'
'/tasks/work', 'Work'
'/tasks/outline', 'Outline'
'/admin/project/admin/:projectId/tree/:treeId/edit', 'Edit'
'/admin/project/admin/:projectId/tree/:treeId/view', 'View'
'/user/', 'User Profile'
'/admin/user/all', 'Users'
'/search', 'Search'
'/library', 'Library'
'/library/project/archive', 'Archive'
'/library/project/archive/:projectId', 'Redirect'
'/library/project/archive/:projectId/edit', 'Edit'
'/library/project/archive/:projectId/team', 'Team'
'/library/project/archive/:projectId/tree/:treeId/edit', 'Edit'
'/library/project/archive/:projectId/tree/:treeId/view', 'View'
'/item', 'Item Router'
'/user/profile/', 'Profile'
'/user/profile/password', 'Change Password'
'/user/profile/preferences', 'Preferences'
'/user/profile/logout', 'Logout'
'/test', 'Test Page'
'/', 'Root'
'/library/project/archive/:projectId/resources/:filePoolId/edit', 'Files'
'/library/project/archive/:projectId/resources/:filePoolId/view', 'Files'
'/project/user/:projectId/resources/:filepoolId/edit', 'Files'
'/project/user/:projectId/resources/:filepoolId/view', 'Files'
'/admin/project/admin/:userId/team/permissions/:teamId/edit', 'Project'
'/admin/project/admin/:projectId/team/rolepermission/:teamRoleId/edit', 'Project'
'/document/:documentId/meta/:metaContext/edit', 'Document'
'/document/:documentId/meta/:metaContext/view', 'Document'

